name: Fastly Cache Purger

on:
  push:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  fastly-cache-purger:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      issues: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: guardian/setup-scala@v1

      - name: Check formatting, run tests, build JAR
        env:
          SBT_JUNIT_OUTPUT: ./junit-tests
        run: sbt 'scalafmtCheck; scalafmtSbtCheck; Test/scalafmtCheck; test; assembly'

      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  #runs even if there is a test failure
        with:
          files: junit-tests/*.xml

      - uses: guardian/actions-riff-raff@v4
        with:
          configPath: riff-raff.yaml
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: Content Platforms::fastly-cache-purger
          buildNumberOffset: 252
          contentDirectories: |
            fastly-cache-purger:
              - target/scala-2.12/fastly-cache-purger.jar
