name: Fastly Cache Purger

on:
  push:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  fastly-cache-purger:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      issues: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt

      - name: Build and test
        env:
          SBT_JUNIT_OUTPUT: ./junit-tests
        run: sbt 'test;assembly'

      - uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()  #runs even if there is a test failure
        with:
          files: junit-tests/*.xml

      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-west-1
          role-to-assume: ${{secrets.GU_RIFF_RAFF_ROLE_ARN}}

      - uses: guardian/actions-riff-raff@v2
        with:
          configPath: riff-raff.yaml
          projectName: Content Platforms::fastly-cache-purger
          buildNumberOffset: 252
          contentDirectories: |
            fastly-cache-purger:
              - target/scala-2.12/fastly-cache-purger.jar